### ISSUE TITLE
[Bug] Errors everywhere after last update

### ISSUE THREAD

**Issue by ostap667inbox** [lobehub/sd-webui-lobe-theme#425] opened 2023-09-19 23:39 UTC
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 📦 SD Wbui 版本或提交 | Version or Commit

1.6.0

### 📦 Lobe Theme 版本或提交 | Version or Commit

3.0.8

### 🐛 问题描述 | Bug Description

A lot of errors in UI, look at screenshot. But no errors visible in console
WebUI doesn't work. I can't do anything, there are error icons everywhere
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/123593542/d9d07e84-3d39-439a-97f2-4cf0144c6200)

**Comment by Amazon90** [comment] 2023-09-20 05:56
That's an error caused by http proxy.Please close it.

**Comment by ostap667inbox** [comment] 2023-09-20 10:28
> That's an error caused by http proxy.Please close it.

Thank you! That really helped.
Are there any domain names that can be set as an exception to the proxy so that I don't have to turn it off every time I use the WebUI?

**Comment by Amazon90** [comment] 2023-09-20 10:52
> > That's an error caused by http proxy.Please close it.
> 
> 
> 
> Thank you! That really helped.
> 
> Are there any domain names that can be set as an exception to the proxy so that I don't have to turn it off every time I use the WebUI?

I think you can use cldflare or v2rayN. They didn't show the error in my test.

**Closed** 2023-09-20 16:16 UTC
Labels: 🐛 Bug
